spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
#    defer-datasource-initialization: true #DB에 초기 데이터 삽입을 위함.
#
#  sql:
#    init:
#      mode: always
      
  profiles:
    include: auth

server:
  address: 0.0.0.0
  port: 8083

